services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - REACT_APP_API_URL=http://localhost:3000/api
    container_name: dashboard-app
    restart: unless-stopped
    networks:
      - dashboard-network
    depends_on:
      - db
    volumes:
      - ./backend/data:/app/backend/data
      - ./logs:/app/logs

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: dashboard-db
    restart: unless-stopped
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  dashboard-network:
    driver: bridge 